version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    platform: linux/x86_64
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    restart: always    
    ports:
      - "${FRONTEND_LOCAL_PORT}:${FRONTEND_DOCKER_PORT}"
    networks:
      - application-net

  backend:
    depends_on:
      - mysqldb
    platform: linux/x86_64  
    env_file: ./.env
    build: .
    container_name: backend
    restart: always
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    networks:
      - application-net
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?useSSL=false",
        "spring.datasource.username" : "${MYSQLDB_USER}",
        "spring.datasource.password" : "${MYSQLDB_ROOT_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.sql.init.mode": "always"
      }'
            
  mysqldb:
    platform: linux/x86_64
    env_file: ./.env
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    networks:
      - application-net
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    volumes:
      - ./mysql_data:/var/lib/mysql
       
      
networks:
  application-net:
    driver: bridge
