apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . | printf "backend-%s" }}

spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.selector.label.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.template.label.appName }}
    spec:
      containers:
        - name: {{ .Values.backend.containerName }}
          image: "{{- .Values.backend.image.repository -}}:{{- .Values.backend.image.tag -}}"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.backend.configMapName }}
