apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "my-chart.fullname" . | printf "frontend-%s" }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.selector.label.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.template.label.appName }}
    spec:
      containers:
        - name: {{ .Values.frontend.containerName }}
          image: "{{- .Values.frontend.image.repository -}}:{{- .Values.frontend.image.tag -}}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}