frontend:
  replicaCount: 1
  selector:
    label:
      appName: frontend
  template:
    label: 
      appName: frontend
  containerName: frontend
  image:
    repository: yashchouhan/frontend:12
    tag: 12
  containerPort: 80

  service:
    selector:
      appName: frontend
    protocol: TCP
    port: 80
    tragetPort: 80

backend:
  replicaCount: 1
  selector:
    label:
      appName: backend
  template:
    label: 
      appName: backend
  containerName: backend
  image:
    repository: yashchouhan/backend-nv1
    tag: 57
  containerPort: 8080
  configMapName: spring-config

  service:
    selector:
      appName: backend
    protocol: TCP
    port: 8080
    tragetPort: 8080

mysqldb:
  serviceName: mysqldb
  replicaCount: 1
  selector:
    selector:
      appName: mysqldb
  template:
    label: 
      appName: mysqldb
  containerName: mysqldb
  image:
    repository: mysql
    tag: 5.7
  containerPort: 3306
  configMapName: mysqldb-config
  volumeMounts:
    name: mysql-data
    mountPath: /var/lib/mysql
  volumes:
    name: mysql-data
    path: /home/opt/db
  rootPassword: yash
  dbName: test
    
  service:
    selector:
      appName: frontend
    protocol: TCP
    port: 80
    tragetPort: 80
