apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: yashchouhan/backend:13
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-config
